main/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import (
    ProductDetailView,
    BaseView,
    AboutView,
    ContactsView,
    ProductListView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    LoginView,
    RegistrationView,
    ProfileView,
    ProductDiscount
)

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('about/', AboutView.as_view(), name='about'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('products/<str:slug>/', ProductListView.as_view(), name='product_list'),
    path('product/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:slug>/', DeleteFromCartView.as_view(), name='remove_from_cart'),
    path('change-qty/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('auth/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('discount/', ProductDiscount.as_view(), name='discount')
]

snowproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import sys
from PIL import Image
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model

from django.utils import timezone
from django.urls import reverse

from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile

User = get_user_model()


class CategoryManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_navbar(self):
        qs = list(self.get_queryset().annotate(models.Count('product')))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=c.product__count, slug=c.slug) for c in qs
        ]
        return data


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)

    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_list', kwargs={'slug': self.slug})


class Product(models.Model):
    MAX_RESOLUTION = (800, 800)
    IMAGE_SIZE = 3145728

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')
    discount = models.BooleanField(default=False, verbose_name='скидка')
    discount_price = models.DecimalField(
        max_digits=9, decimal_places=2, null=True, blank=True, verbose_name='Скидочная цена'
    )
    size = models.CharField(max_length=255, verbose_name='Ростовка')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        image = self.image
        img = Image.open(image)
        new_image = img.convert('RGB')
        resized_new_image = new_image.resize((600, 700), Image.ANTIALIAS)
        filestream = BytesIO()
        resized_new_image.save(filestream, 'JPEG', quality=90)
        filestream.seek(0)
        name = '{}'.format(self.image.name)
        self.image = InMemoryUploadedFile(
            filestream, 'ImageField', name, 'jpeg/image', sys.getsizeof(filestream), None
        )
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})


class CartProduct(models.Model):
    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    product = models.ForeignKey(Product, verbose_name='Товар', on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт: {} (для корзины)".format(self.product.title)

    def save(self, *args, **kwargs):
        if self.product.discount:
            self.final_price = self.qty * float(self.product.discount_price)
        else:
            self.final_price = self.qty * self.product.price
        super().save(*args, **kwargs)


class Cart(models.Model):
    owner = models.ForeignKey('Customer', null=True, verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    order = models.ManyToManyField('Order', verbose_name='Заказы покупателя', related_name='related_customer')

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)


class Order(models.Model):

    STATUS_NEW ='new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ выполнен')
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка')
    )

    customer = models.ForeignKey(
        Customer,
        verbose_name='Покупатель',
        related_name='related_orders',
        on_delete=models.CASCADE
    )
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=255, verbose_name='Номер телефона')
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name='Адрес', null=True, blank=True)
    status = models.CharField(max_length=100, verbose_name='Статус заказа', choices=STATUS_CHOICES, default=STATUS_NEW)
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Тип заказа',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Создание заказа')
    order_date = models.DateField(verbose_name='Дата получения заказа', default=timezone.now)

    def __str__(self):
        return str(self.id)

main/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Order


class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = 'Дата получения заказа'

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'order_date', 'comment'
        )


class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь с логином {username} не найден')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError('Неверный пароль')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ('username', 'password')


class RegistrationForm(forms.ModelForm):

    confirm_password = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    phone = forms.CharField(required=False)
    address = forms.CharField(required=False)
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'
        self.fields['confirm_password'].label = 'Подтвердите пароль'
        self.fields['phone'].label = 'Номер телефона'
        self.fields['first_name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['address'].label = 'Адрес'
        self.fields['email'].label = 'Электронная почта'

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Данный почтовый адресс уже зарегистрирован в системе')
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Имя {username} занято')
        return username

    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('Пароли не совпадают')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password', 'first_name', 'last_name', 'address', 'phone', 'email']

main/templates/main/about.html
{% extends 'main/base.html' %}

{% block content %}
    <nav aria-label="breadcrumb" class="mt-3" style="margin-left: 40px">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
        <li class="breadcrumb-item active" aria-current="page">О нас</li>
      </ol>
    </nav>
    <div class="d-flex flex-column" style="margin-bottom: 50px; margin-top: 15px">
        <div class="p2">
            <h2 class="text-center">О SnowSHOP</h2>
            <hr>
            <h4>Интернет-магазин SnowSHO только начинает свою деятельность как интернет магазин снаряжения для зимних видов спорта. Всё началось с горнолыжного курорта логойск, который до сих пор является одним из самых любых мест для сноубордистов в Беларуси.
                Мы выбрали сноубординг, вейкбординг, серфинг, сап сёрфинг, скейтбординг и лонгбординг как основные виды активности, которыми мы занимаемся, продаём и продвигаем. Мы не останавливаемся на этом и постоянно думаем над новыми интересными направлениями.
                Мы предлагаем лучшие бренды в нашем магазине по всем направлениям деятельности: SLINGSHOT, ION, LANDYACHTZ, LONG ISLAND, SKATE MAFI.
            </h4>
        </div>
    </div>
{% endblock content %}

main/templates/main/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
    (function($) {
        $('#id_discount').on('click', function(){
            if($('#id_discount').prop('checked') == true){
                $('#id_discount_price').prop('readonly', false)
                $('#id_discount_price').val('')
                $('#id_discount_price').css('background', 'white')
            }else{
                $('#id_discount_price').prop('readonly', true)
                $('#id_discount_price').val('')
                $('#id_discount_price').css('background', 'lightgray')
            }
        })
    })(django.jQuery);
</script>
{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Homepage - Start Bootstrap Template</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" style="font-size: 30px" href="{% url 'base' %}" >SnowSHOP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'about' %}">О нас</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contacts' %}">Контакты</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'discount' %}">Скидочный товар</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                {% for category in categories %}
                                <li><a class="dropdown-item" href="{% url 'product_list' slug=category.slug %}">{{ category.name }} ({{ category.count }})</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        {% if not request.user.is_authenticated %}
                        <li>
                            <a class="nav-link text-grey" href="{% url 'login' %}">Авторизация</a>
                        </li>
                        <li>
                            <a class="nav-link text-grey" href="{% url 'registration' %}">Регистрация</a>
                        </li>
                        {% endif %}
                        <li style="list-style-type: none;" class="nav-item">
                            {% if request.user.is_authenticated %}
                                <span class="navbar text text-grey">Здравствуйте, <span class="badge badge-danger">
                                <a style="text-decoration: none; font-size: 20px; color: black" href="{% url 'profile' %}">{{ request.user.username }}</a>
                                </span> | <a href="{% url 'logout' %}" style="color: darkred; text-decoration: none; margin-right: 5px">Выйти</a></span>
                            {% endif %}
                        </li>
                    </ul>
                    <form class="d-flex">
                        <button type="button" class="btn btn-outline-success and-all-other-classes">
                            <a href="{% url 'cart' %}" style="color:black">
                                <i class="bi-cart-fill me-1"></i>
                                Корзина
                                <span class="badge bg-dark text-white ms-1 rounded-pill">{{ cart.total_products}}</span>
                            </a>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
        <header>
            <div class="row" style="margin-left: 0; margin-right: 0;">
                <div class="col" style="padding-left: 0; padding-right:0;">
                    <div class="img-wrap" style="position: relative; border-right: orange">
                        <a href="https://logoisk.by/">
                            <img src="/media/one.jpg" class="img-fluid" style="width: 100%; height: 250px;">
                            <h2 style="position: absolute;left: 1rem;bottom: 3rem;width: 100%;color: orange">Горнолыжный курорт Логойск</h2>
                            <h3 style="position: absolute;left: 10rem;bottom: 1rem;width: 100%;color: orange">Сейчас {{ weather_lahoysk }}°</h3>
                        </a>
                    </div>
                </div>
                <div class="col" style="padding-left: 0; padding-right:0;">
                    <div class="img-wrap" style="position: relative;">
                        <a href="https://silichy.by/">
                            <img src="/media/two.jpg" class="img-fluid" style="width: 100%; height: 250px;">
                            <h2 style="position: absolute;left: 0rem;bottom: 12rem;width: 100%;color: orange">Горнолыжный курорт Силичи</h2>
                            <h3 style="position: absolute;left: 0rem;bottom: 9rem;width: 100%;color: orange">Сейчас {{ weather_silichi }}°</h3>
                        </a>
                    </div>
                </div>
            </div>
        </header>
        <section class="py-5">
            {% block content %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                      <strong>{{ message }}</strong>
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
            <div class="container px-4 px-lg-5 mt-5 col-sm-7">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for product in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <a href="{{ product.get_absolute_url }} "><img class="card-img-top" src="{{ product.image.url }}"/></a>
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h5 class="fw-bolder"><a href="{{ product.get_absolute_url }} ">{{ product.title }}</a></h5>
                                    {{ product.price }} руб.
                                </div>
                            </div>
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'add_to_cart' slug=product.slug %}">Add to cart</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% for product in product_discount %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                            <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}"/></a>
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h5 class="fw-bolder"><a href="{{ product.get_absolute_url }} ">{{ product.title }}</a></h5>
                                    <span class="text-muted text-decoration-line-through">{{ product.price }}</span>
                                    {{ product.discount_price }} руб.
                                </div>
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'add_to_cart' slug=product.slug %}">Add to cart</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endblock %}
            </section>
            <footer class="py-5 bg-dark">
                <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
            </footer>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

main/templates/main/cart.html
{% extends 'main/base.html' %}

{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>{{ message }}</strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
<h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %} пуста{% endif %}</h3>
<nav aria-label="breadcrumb" class="mt-3" style="margin-left: 40px">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
    <li class="breadcrumb-item active" aria-current="page">Корзина</li>
  </ol>
</nav>
{% if cart.products.count %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">Наименование</th>
            <th scope="col">Ихображение</th>
            <th scope="col">Цена</th>
            <th scope="col">Кол-во</th>
                <th scope="row">Общая цена</th>
            <th scope="col">Действие</th>
        </tr>
    </thead>
<tbody>
{% for item in cart.products.all %}
<tr>
    <th scope="row">{{ item.product.title }}</th>
    <td><img class="img-fluid" width="150" height="200" src="{{ item.product.image.url }}"></td>
    {% if item.product.discount %}
        <td>{{ item.product.discount_price }} руб.</td>
    {% else %}
        <td>{{ item.product.price }} руб.</td>
    {% endif %}
    <td>
        <form action="{% url 'change_qty' slug=item.product.slug %}" method="POST">
            {% csrf_token %}
            <input type="number" class="form-control" name="qty" style="width: 70px" min="1" value="{{ item.qty }}">
            <br>
            <input type="submit" class="btn btn-primary" value="Изменить кол-во">
        </form>
    </td>
        <td>{{ item.final_price }} руб.</td>
    <td>
        <a href="{% url 'remove_from_cart' slug=item.product.slug %}"><button class="btn btn-danger">Удалить из корзины</button></a>
    </td>
</tr>
{% endfor %}
<tr>
    <td colspan="2"></td>
    <td>Итого:</td>
    <td>{{ cart.total_products }}</td>
    <td><strong>{{ cart.final_price }} руб.</strong></td>
    <td><a href="{% url 'checkout'  %}"><button class="btn btn-primary">Перейти к оформлению</button></a></td>
</tr>
</tbody>
</table>
{% endif %}
{% endblock content %}

main/templates/main/checkout.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h3 class="text-center mt-5 mb-5">Оформление заказа</h3>
    <table class="table">
    <thead>
        <tr>
            <th scope="col">Наименование</th>
            <th scope="col">Ихображение</th>
            <th scope="col">Цена</th>
            <th scope="col">Кол-во</th>
                <th scope="row">Общая цена</th>
        </tr>
    </thead>
<tbody>
{% for item in cart.products.all %}
<tr>
    <th scope="row">{{ item.product.title }}</th>
    <td><img class="img-fluid" width="150" height="200" src="{{ item.product.image.url }}"></td>
    <td>{{ item.product.price }} руб.</td>
    <td>{{ item.qty }}</td>
        <td>{{ item.final_price }} руб.</td>
</tr>
{% endfor %}
<tr>
    <td colspan="2"></td>
    <td>Итого:</td>
    <td>{{ cart.total_products }}</td>
    <td><strong>{{ cart.final_price }} руб.</strong></td>
</tr>
</tbody>
</table>
<hr>
<h3 class="text-center mt-5 mb-5">Форма заказа</h3>
<div class="col-sm-15 d-flex justify-content-center">
<form action="{% url 'make_order' %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-success btn-block mb-3" value="Оформить заказ">
</form>
</div>
{% endblock content %}

main/templates/main/profile.html
{% extends 'main/base.html' %}

{% block content %}
<div class="text-center mt-3 mb-3">
<h3>Заказы пользователя {{ request.user.username }}</h3>
<nav aria-label="breadcrumb" class="mt-3" style="margin-left: 40px">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
    <li class="breadcrumb-item active" aria-current="page">Личный кабинет</li>
  </ol>
</nav>
{% if not orders.count %}
    <div class="col-md-12" style="margin-top: 70px; margin-bottom: 250px;">
        <h3>У вас нет заказов! <a style="text-decoration: none;" href="{% url 'base' %}">На главную</a> </h3>
    </div>
    {% else %}
    <div class="col-md-12" style="margin-top: 70px; margin-bottom: 250px;">
        <table class="table">
            <thead>
                <th scope="col">Номер</th>
                <th scope="col">Статус</th>
                <th scope="col">Сумма</th>
                <th scope="col">Товар - кол-во</th>
                <th scope="col">Дополнительно</th>
            </thead>
            <tbody>
                {% for order in orders %}
                    <tr>
                        <th scope="row">{{ order.id }}</th>
                        <td>{{ order.get_status_display }}</td>
                        <td>{{ order.cart.final_price }} руб.</td>
                        <td>
                            <ul class="navbar-nav">
                                {% for item in order.cart.products.all %}
                                    <li>{{ item.product.title }} - {{ item.qty }} шт.</li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td>
                            <button class="btn btn-info" data-bs-toggle="modal" data-bs-target="#exampleModal-{{ order.id }}">Дополнительно</button>
                            <div class="modal fade" id="exampleModal-{{ order.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                              <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Детализация заказа</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                  </div>
                                  <div class="modal-body">
                                    <h4 class="text-center">Товар</h4>
                                      <table class="table">
                                          <thead>
                                            <tr>
                                                <th scope="col">Наименование</th>
                                                <th scope="col">Изображение</th>
                                                <th scope="col">Цена</th>
                                                <th scope="col">Кол-во</th>
                                                <th scope="col">Общая цена</th>
                                            </tr>
                                          </thead>
                                          <tbody>
                                            {% for item in order.cart.products.all %}
                                                <tr>
                                                    <th scope="row">{{ item.product.title }}</th>
                                                    <td class="w-25"><img src="{{ item.product.image.url }}" class="card-img-top"></td>
                                                    <td><strong>{{ item.product.price }} руб.</strong></td>
                                                    <td>{{ item.qty }}</td>
                                                    <td>{{ item.final_price }} руб.</td>
                                                </tr>
                                            {% endfor %}
                                                <tr>
                                                    <td colspan="2"></td>
                                                    <td>Итого: </td>
                                                    <td>{{ order.cart.total_products }}</td>
                                                    <td><strong>{{ order.cart.final_price }} руб.</strong></td>
                                                </tr>
                                          </tbody>
                                      </table>
                                        <hr>
                                        <h4 class="text-center"></h4>
                                        <p>Имя: <strong>{{ order.first_name }}</strong></p>
                                        <p>Фамилия: <strong>{{ order.last_name }}</strong></p>
                                        <p>Телефон: <strong>{{ order.customer.phone }}</strong></p>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                                  </div>
                                </div>
                              </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}
</div>
{% endblock content %}